### ISSUE TITLE
Ensure that all media files are uploaded

### ISSUE THREAD

**Issue by tintou** [elementary/houston#336]
On the Components-amd64.yml.gz is specified this directory MediaBaseUrl: …/apphub/media/xenial
Please make sure that it exists and that all media are automatically uploaded to this repository (it's mostly useful for Screenshots)

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40521862-ensure-that-all-media-files-are-uploaded?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github).

**Comment by btkostner** [comment]
What file are you checking? According to the `Components-amd64.yml.gz` [here](https://packages.elementary.io/apphub/dists/xenial/main/appstream/) it should point to the appstream domain, which is controlled by appstream generator.

```yml
---
File: DEP-11
Version: '0.8'
Origin: apphub-xenial-main
MediaBaseUrl: https://appstream.elementary.io/apphub/media/xenial
Priority: 13
Time: 20161116T032050
```
